kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  BG_COLOR: '#FF0000' # Red background color
  FONT_COLOR: '#FFFFFF' # White font color
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
